name: Deploy
on:
  schedule:
  - cron: '0 6 * * *'
  workflow_dispatch:
jobs:
  Build:
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: '2.17'
      - run: |
          pip install virtualenv
          virtualenv .venv
          .venv/bin/pip install feedparser pytidylib
          cd rawdog-2.23
          ../.venv/bin/python setup.py install
          cd -
          .venv/bin/rawdog --dir . --no-locking --update --write
  Deploy:
    uses: seanh/ghp-static/.github/workflows/static.yml@main
    with:
      path: "site/"
    permissions:
      contents: read
      pages: write
      id-token: write
