name: Build & Deploy
on:
  schedule:
  - cron: '0 6 * * *'
  workflow_dispatch:
jobs:
  Build_and_Deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    container:
      image: python:2.7.18-buster
    steps:
      - name: Cache the state file
        uses: actions/cache@v3
        with:
          path: state
          key: state
      - uses: actions/checkout@v3
      - run: |
          pip install virtualenv
          virtualenv .venv
          .venv/bin/pip install feedparser
          cd rawdog-2.23
          ../.venv/bin/python setup.py install
          cd -
          .venv/bin/rawdog --dir . --no-locking --update --write
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
